# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# When creating a new user, do not specify the authentication_token parameter, it will be autogenerated on user create.
# Only for development and backtesting do we use these predefined authenication tokens below.
User.create(email: 'oanda_trader@translate3d.com', password: 'adminadmin', password_confirmation: 'adminadmin', authentication_token: 'TFq61Z7tP6A3Y18Lzz2j')
User.create(email: 'oanda_worker@translate3d.com', password: 'adminadmin', password_confirmation: 'adminadmin', authentication_token: 'QcABSZSGdhGC5FcxPUrL')
